baseURL = 'https://kosmosghost.github.io/'
languageCode = 'en-us'
title = 'KosmosGhost Site'
theme = "kosmosghost_blog"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3